spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: vedant
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      secret: ZCU9gTY/qD2PRjt+ENxyItf1ba5Bl+lRXqtkeg6xIhaqvPcn8TSsjy0kkyocQoX/



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8093
