spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage_service
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${java.io.tmpdir}
  mvc:
    content negotiation:
      favor-parameter: true
      media-types:
        json: application/json
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8091

app:
  image-directory: uploads/
  image-base-url: http://localhost:8091/images