version: '3.8'

x-variables:
  network_name: &network_name microservices-net
  mysql_root_password: &mysql_root_password root
  mysql_user: &mysql_user vedant

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: *mysql_root_password
      MYSQL_USER: *mysql_user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - *network_name
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  image-storage-service:
    build: ./services/image-storage-service
    container_name: image-storage-service
    environment:
      MYSQL_USER: *mysql_user
      MYSQL_PASSWORD: *mysql_root_password
    ports:
      - "8091:8091"
    networks:
      - *network_name
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  image-container-service:
    build: ./services/image-container-service
    container_name: image-container-service
    environment:
      MYSQL_USER: *mysql_user
      MYSQL_PASSWORD: *mysql_root_password
    ports:
      - "8090:8090"
    networks:
      - *network_name
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  config-server:
    build: ./services/config-server
    container_name: config-server
    ports:
      - "8889:8889"
    networks:
      - *network_name
    restart: unless-stopped
  discovery-server:
    build: ./services/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - *network_name
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge