spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: image-storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/storage_service
    username: root
    password: vedant
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${java.io.tmpdir}
  mvc:
    content negotiation:
      favor-parameter: true
      media-types:
        json: application/json
    pathmatch:
      matching-strategy: ant_path_matcher

  resilience4j.circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        ringBufferSizeInClosedState: 100
        ringBufferSizeInHalfOpenState: 10

  resilience4j.retry:
    instances:
      myService:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException

  resilience4j.timelimiter:
    instances:
      myService:
        timeoutDuration: 5s

server:
  port: 8091

app:
  image-directory: uploads/
  image-base-url: http://localhost:8091/images

